version: '3.8'

services:
  sketch-it-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ..:/app
      - /app/.venv  # Exclude virtual environment
    networks:
      - sketch-it-network
    restart: unless-stopped

  # Optional: Add Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sketch-it-network
    restart: unless-stopped

networks:
  sketch-it-network:
    driver: bridge

volumes:
  redis_data:
